name: Release
on:
  push:
    tags:
      - 'v*-okno'
  workflow_dispatch:
    inputs:
      tag:
        description: "Тег релиза (уже запушенный), например v1.0.0-okno"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-release:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions: write-all
    with:
      upload-artifact: true
      tag-name: "${{ inputs.tag || github.ref_name }}"
      channel: "prod"
